# Generated by Django 4.1.3 on 2022-11-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Mavzu")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Sarlavha"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kirish vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgarish vaqti"),
                ),
                (
                    "photos",
                    models.ImageField(
                        blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Rasm"
                    ),
                ),
                ("is_bool", models.BooleanField(verbose_name="bool")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangoapp.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ma'lumot",
                "verbose_name_plural": "Ma'lumotlar",
                "ordering": ["created_at"],
            },
        ),
    ]
