# Generated by Django 4.1.3 on 2022-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Ko'rinishlar"),
        ),
    ]
